//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4600Project.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_4600Project.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caldendar Requirements
        ///
        ///Team Members
        ///
        ///Daphne Williams
        ///David Hernandez
        ///
        ///Purpose
        ///
        /////
        ///
        ///Requirements
        ///
        ///1. Name: addEvent
        ///   Type: Functional
        ///   Summary: Events can be added to the calendar program by the user.  
        ///2. Name: editEvent
        ///   Type: Functional
        ///   Summary: The user(s) should be able to edit the event(s) added to the calendar. 
        ///3. Name: deleteEvent
        ///   Type: Functional
        ///   Summary: The user(s) should be able to delete any individual event if need be.
        ///4. Name: clearCalendar
        ///   Type: Func [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Requirements {
            get {
                return ResourceManager.GetString("Requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///VISION DOCUMENT
        /// CSCI-4600
        ///
        ///
        ///Daphne Williams &amp; David Hernandez
        ///
        ///
        ///
        ///
        ///1 Introduction
        ///
        ///
        ///1.1 Purpose
        ///
        ///The main purpose of this vision document is to outline the vital requirements, functions, and features of
        ///this project. 
        ///The focus is to create a blueprint for the program and detailing the necessary libraries, the
        ///target users, as well as the stakeholder’s abilities.
        ///
        ///
        ///1.2 Scope
        ///
        ///This Vision Document applies to the Calendar Project, name TBD, which will be developed by Daphne 
        ///Williams and David He [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Vision_Document {
            get {
                return ResourceManager.GetString("Vision_Document", resourceCulture);
            }
        }
    }
}
